sudo: false
language: ruby
cache: bundler
script: "TESTOPTS=-v bundle exec rake test"
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-9.0.5.0
  - jruby-head
  - rbx
matrix:
  include:
    - rvm: 2.1
      gemfile: gemfiles/2.1-Gemfile
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx
    - rvm: ruby-head
